### ISSUE TITLE
Specifications across different versions

### ISSUE THREAD

**Issue by chason-choate-trilliant** [LiveOakLabs/terraform-provider-readme#83]
First off, I want to say thanks for creating this. The docs and examples are great.

I'm having an issue with multiple versions so wanted to drop a note here and see if perhaps I'm doing something incorrectly. Here's my directory structure for reference:

```
main.tf
versions/
    v1-0-0/
        main.tf
        version.tf <-- references the default stable 1.0 version
        apis.tf <-- Configures a single OpenAPI schema
    v1-1-0/
        main.tf
        version.tf <-- references a forked version 1.1.0 from 1.0
        apis.tf <-- Configures a newer OpenAPI schema
```

I'm getting a consistent failure to create the `v1-1-0/apis.tf` resources saying the following (editing out some stuff):

```
│ Error: Unable to read API specification: error getting specification: unable to get specification id 1234: [<list of specs for the stable version>]
│
│   with module.v1-0.readme_api_specification.foo,
│   on versions/v1-0/apis.tf line 1, in resource "readme_api_specification" "foo":
│    1: resource "readme_api_specification" "foo" {
│
│ error getting specification: unable to get specification id 1234: [<list of specs for the stable version>]
```

Looking at the [Readme Spec API](https://docs.readme.com/main/reference/getapispecification) it seems this may be the cause:

```
x-readme-version
string
Version number of your docs project, for example, v3.0. By default the main project version is used. To see all valid versions for your docs project call https://docs.readme.com/main/reference/version#getversions.
```

It seems it is only retrieving the specs for the current stable version and therefore fails to reference the new api spec once created.

To be fair, this may not be a valid setup so if you have some better ideas on structure those thoughts would be greatly appreciated. Thanks!

**Comment by joshbeard** [comment]
Hi @chason-choate-trilliant! Thanks for the feedback and for reporting this. After digging into this some, it appears to be caused by a silly bug in the API client that affects paginated requests, causing the `Version` key to be ignored.
I've opened https://github.com/LiveOakLabs/readme-api-go-client/pull/39 to fix this and expect an updated release to be published to the Terraform registry Wednesday with that fix included.

Your structure looks sensible to me. To be candid, there's more testing needed for managing multiple versions in ReadMe. It's complicated by the fact that creating a version copies the contents from the source version, creating a bunch of unmanaged resources with it.

**Comment by joshbeard** [comment]
Hi @chason-choate-trilliant - 0.1.17 is published with that fix included. Can you give it a try with that version when you get a chance and let me know how it goes? Thanks!

**Comment by chason-choate-trilliant** [comment]
Awesome! Changing only the provider version allowed the API specs to be created. Thanks again for the effort and I'll let you know if I find anything else.
